### ISSUE TITLE
Not reported error when trying to quantize a jpg image

### ISSUE THREAD

**Issue by rogercampos** [rogercampos/png_quantizator#1]
ruby raises a Broken pipe when trying to write into the stdin the contents of a jpeg file, since the binary automatically closes the pipe after detecting the error. The exception is not captured.

**Comment by PikachuEXE** [comment]
Not sure if related

Got error broken pipe for some images

### Env 
Custom Docker image based on https://github.com/phusion/baseimage-docker
`pngquant` install by `apt-get`
```
pngquant, 2.5.0 (June 2015), by Greg Roelofs, Kornel Lesinski.
   Using libpng 1.2.54.

Linux 4cc0fc22f0de 4.9.44-linuxkit-aufs #1 SMP Fri Aug 25 10:00:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

### Backtrace
```
/usr/local/lib/ruby/gems/2.4.0/gems/png_quantizator-0.2.1/lib/png_quantizator.rb:32:in `write'
/usr/local/lib/ruby/gems/2.4.0/gems/png_quantizator-0.2.1/lib/png_quantizator.rb:32:in `block in quantize_to'
/usr/local/lib/ruby/2.4.0/open3.rb:205:in `popen_run'
/usr/local/lib/ruby/2.4.0/open3.rb:95:in `popen3'
/usr/local/lib/ruby/gems/2.4.0/gems/png_quantizator-0.2.1/lib/png_quantizator.rb:31:in `quantize_to'
/usr/local/lib/ruby/gems/2.4.0/gems/png_quantizator-0.2.1/lib/png_quantizator.rb:20:in `block in quantize!'
/usr/local/lib/ruby/2.4.0/tempfile.rb:295:in `open'
/usr/local/lib/ruby/gems/2.4.0/gems/png_quantizator-0.2.1/lib/png_quantizator.rb:19:in `quantize!'
/usr/local/lib/ruby/gems/2.4.0/gems/piet-0.2.6/lib/piet.rb:13:in `pngquant'
```

### Original image example
![7692127](https://user-images.githubusercontent.com/1018543/33422565-1195d384-d5f1-11e7-902f-0efca973db66.png)
